AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 180
    Handler: index.handler
    Environment:
      Variables:
        USERS_TABLE_NAME: !Ref UsersTable

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./hello
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
  SaveFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.save
      Runtime: nodejs16.x
      CodeUri: ./save
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /users
            Method: POST
  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: ./list
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /users
            Method: GET
  ShowFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./show
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET

  #DynamoDB
  UsersTable:
    Type: AWS::Serverless::SimpleTable

Outputs:
  MyApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"