AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  SaveFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.save
      Runtime: nodejs16.x
      CodeUri: ./save
      Events:
        Api:
          Type: Api
          Properties:
            Path: /users
            Method: POST